### ISSUE TITLE
low-pri: link to this github from the about screen in XMPlay

### ISSUE THREAD

**Issue by dhry** [KelticDanor/xmp-SIDevo#1]
Hey there!

Super low priority - would it be possible to include a hyperlink to this Github repo in the about screen for the plugin in XMplay? That way we could just click to get the latest version as and when you release it. A link to https://support.xmplay.com/files_view.php?file_id=731 could be good as well - or instead.

Cheers
Dhry

**Comment by KelticDanor** [comment]
This has been added for the 4.3 with a couple of buttons for the git and support site pages.
