### ISSUE TITLE
When default duration is set to 0, songlengths are no longer honored

### ISSUE THREAD

**Issue by ImreOlajos** [KelticDanor/xmp-SIDevo#3]
I have the HVSC DOCUMENTS path set, SIDevo shows the status as "Songlengths & STIL found", yet, when I set the "Default duration" to 0 the songlengths for SIDs played from within HVSC are no longer honored. Any value other than a 0 for default duration "enables" songlengths again.

**Comment by KelticDanor** [comment]
This has been fixed for the 4.3, nice catch!
