### ISSUE TITLE
Missing songlengths.md5 file causes infinite loop

### ISSUE THREAD

**Issue by dhry** [KelticDanor/xmp-SIDevo#4]
If you configure the plugin to access the songlengths.md5 file at a particular location (successfully) then completely move the XMPlay and \plugins subfolder to a different drive path, when SidEVO starts you get the attached dialog and no amount of attempting to close it or okay it will cause it to stop looking. Have to endtask the app.

![image](https://github.com/KelticDanor/xmp-SIDevo/assets/4991066/a9f371e9-f940-4793-ac72-0e84cd00bab4)

Only fix appears to be to manually edit the file path in the xmplay.ini file.

Suggestion: If file is not found, app should ask "search for the file?" or similar and allow the user to choose the new file and location.

**Comment by KelticDanor** [comment]
Not able to reproduce this at the moment but I'll just put in a fix that if it fails it won't pop up again until config is re-saved or it is restarted. Think that will do the trick?

**Comment by KelticDanor** [comment]
The latest version should suppress errors after the first one until the config is opened again.
