### ISSUE TITLE
Feature request - mono mode selectable

### ISSUE THREAD

**Issue by dhry** [KelticDanor/xmp-SIDevo#5]
Could you implement a simple stereo/mono channel output switcher within the plugin config pls? I just listened to \MUSICIANS\N\Nordischsound\Get_Lucky_2SID.sid and the stereo seperation on it is pretty significant. I have stereo on for everything else (ie regular music) but would like to selectively default to mono just for SIDs so they don't sound wackadoodle, especially on headphones.

That surround sound mode mentioned in another feature request would be amazing, but if it can't be done, it can't be done.

Thx!
Dhry

**Comment by KelticDanor** [comment]
I can try putting in an option to set the mono/stereo setting of libsidplayfp, currently it just goes by whatever XMPlay has set. If you set XMPlay to mono does it work like you expect? If so I think a setting like that will help.

As for surround (and the other request) the issue is I don't really know what that means to the actual audio I get from libsidplayfp. If you can point me in the right direction I can try and figure something out but I've never seen any other players provide something like that for SID either so never had much to go by.

**Comment by KelticDanor** [comment]
Maybe I should revisit sidex, did Malades version surround work like you expect it to?

**Comment by dhry** [comment]
Aight, Git didn't notify me at all of your responses! Let me check and I'll get back to you. 

Edit: Quick note though, I definitely don't want to have to switch XMplay manually to mono to play SIDs and then back to stereo to play the 99% of other stuff through it. Yes I could do that but it would be plenty inconvenient.

**Comment by dhry** [comment]
Best SID plugin for XMPlay to look at surround functionality is Fraggie's v37.1. Install it and have a listen to what it does with these options enabled.

https://support.xmplay.com/files_view.php?file_id=504

![image](https://github.com/user-attachments/assets/d58fe125-9275-4591-9823-bb51661bf51e)

**Comment by dhry** [comment]
I don't know if I have the Malade version, do you have a link? We can move this conversation to DM on the un4seen forums if you like.

Dhry

**Comment by KelticDanor** [comment]
> Aight, Git didn't notify me at all of your responses! Let me check and I'll get back to you.
> 
> Edit: Quick note though, I definitely don't want to have to switch XMplay manually to mono to play SIDs and then back to stereo to play the 99% of other stuff through it. Yes I could do that but it would be plenty inconvenient.

Oh I don't recommend doing it, it is just a test. If you do switch it to mono does it work as you would expect? If so I can put in an easy "force mono" checkbox/option.


> Best SID plugin for XMPlay to look at surround functionality is Fraggie's v37.1. Install it and have a listen to what it does with these options enabled.
> https://support.xmplay.com/files_view.php?file_id=504

Yeah I know but I don't know how he did it or where to start. 😕 You can still get (at least a version) of Malades plugin here https://support.xmplay.com/files_view.php?file_id=720 It does have some code related to surround sound of some sort and I think I may be able to migrate that to this plugin with a bit of effort but I don't want to go too far down that road if the results are not acceptable.

**Comment by dhry** [comment]
God. Reason github wasn't notifying me by email is that I didn't have "notify me by email" enabled. PEBCAK! Fixed.

Re mono, yes, that mode in XMplay output → channels works great. I tested it with \MUSICIANS\M\Mahoney\Stereophonik_6581_2SID.sid

Force mono, if easy to implement, would be great. No rush. Happy to test as always.

Dhry

**Comment by KelticDanor** [comment]
Here is a test version with a few changes, check txt file for details.
[xmp-sidevo.4.7alpha.zip](https://github.com/user-attachments/files/16659407/xmp-sidevo.4.7alpha.zip)

I tried to migrate the "surround" or as he puts it, stereo enhancements from Malades SidEX (https://support.xmplay.com/files_view.php?file_id=720) but I can't tell any difference... it's possible I did it wrong.

I'm actually happy to add a surround sound option in but I don't even know what it means sound wise or what the end result is supposed to be like. I'd welcome any pointers in the right direction but as is I don't know what "surround" means anymore than your average horse.

**Comment by dhry** [comment]
Tried it out. Good news is that the mono mode works perfectly! Check that one off the list - thank you!

The surround experimental mode doesn't work though. I'm not an expert but I think what the idea of this type of functionality is, is to somewhat duplicate/echo/slightly reverb (MAYBE) one channel's output across to the other side. Best way to figure it out is to use SidEX 3.0 on either \MUSICIANS\M\Mahoney\Stereophonik_6581_2SID.sid or Stereophonik_8580_2SID.sid. SidEX's options panel allows you to enable or disable 1-sid or 2-sid surround, and you can hear the effect instantly when you check or uncheck either or both of them. Stereophonik very distinctly comes out of one speaker and then the other at the start. Listening to that on headphones would be a bit disconcerting, but with the SidEX surround mode the channel sounds are smeared across to the other side. Close to mono but still with some separation. That's just my guess and perception from listening to the effect.

For me it's honestly not a big deal, could be a project/challenge for the future of this plugin. For now I'm happy with the mono mode! I wonder if maybe Fiemost might be able to point you in the right direction? Otherwise, there's a guy named Christopher Snowhill ("[Kode54](https://github.com/kode54)") who has done a crapton of work on all sorts of music plugins, VGM stuff etc for Foobar2000 - he might be able to point you in the right direction. If you're on Mastodon you can find him here - https://social.losno.co/@chris

Cheers
Dhry

**Comment by KelticDanor** [comment]
I'll just take out the surround experiment for now and release the current fix.

**Comment by dhry** [comment]
Great work. Cheers! 

DRS
